repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
        -   id: ruff-format
        -   id: ruff
            args: [--fix]

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.9.2
  hooks:
    - id: uv-lock