name: update data
on:
  schedule:
    # At 08:00 on every Monday
    - cron: '0 8 * * 1'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if it's the second Monday of the month or manual trigger
        id: check_second_monday
        run: |
          echo "RUN_JOBS=$(python -c "import datetime, sys; today=datetime.date.today(); first_day=today.replace(day=1); first_monday=first_day+datetime.timedelta(days=(7-first_day.weekday())%7); second_monday=first_monday+datetime.timedelta(days=7); print('true' if today==second_monday or '${{ github.event_name }}'=='workflow_dispatch' else 'false')")" >> $GITHUB_ENV
        shell: bash

      - uses: actions/checkout@v3
        if: env.RUN_JOBS == 'true'
      
      - name: Setup uv
        if: env.RUN_JOBS == 'true'
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --python 3.13
          echo "=== Download Started at $(date) ==="
          echo "System info: $(uname -a)"
          echo "Available memory: $(free -h)"
          echo "Disk space: $(df -h .)"

      - name: Download latest changeset with discussions
        if: env.RUN_JOBS == 'true'
        run: |
          wget --progress=dot:giga --timeout=3600 --tries=3 https://planet.openstreetmap.org/planet/discussions-latest.osm.bz2

      - name: Process changeset and comments to tables
        if: env.RUN_JOBS == 'true'
        run: |
          # Run the actual processing
          uv run scripts/changeset_osm_to_raw_data.py discussions-latest.osm.bz2 changeset_data_raw changeset_comments_data --comments-ignore-current-month
          # delete discussions file after processing to save disk space
          rm -f discussions-latest.osm.bz2

      - name: Enrich changeset table
        if: env.RUN_JOBS == 'true'
        run: |
          # Run enrichment for the last complete month
          uv run scripts/changeset_raw_data_to_data.py changeset_data_raw changeset_data --last-complete-month

      - name: Download latest notes
        if: env.RUN_JOBS == 'true'
        run: |
          wget --progress=dot:giga --timeout=3600 --tries=3 https://planet.openstreetmap.org/notes/planet-notes-latest.osn.bz2

      - name: Process notes and comments to tables
        if: env.RUN_JOBS == 'true'
        run: |
          # Run the actual processing
          uv run scripts/notes_osm_to_data.py planet-notes-latest.osn.bz2 notes_data notes_comments_data --ignore-current-month
          # delete notes file after processing to save disk space
          rm -f planet-notes-latest.osn.bz2

      - name: Upload data to Hugging Face
        if: env.RUN_JOBS == 'true'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          bash scripts/upload_data_to_huggingface.sh