name: update data
on:
  schedule:
    # At 08:00 on every Monday
    - cron: '0 8 * * 1'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if it's the second Monday of the month or manual trigger
        id: check_second_monday
        run: |
          echo "RUN_JOBS=$(python -c "import datetime, sys; today=datetime.date.today(); first_day=today.replace(day=1); first_monday=first_day+datetime.timedelta(days=(7-first_day.weekday())%7); second_monday=first_monday+datetime.timedelta(days=7); print('true' if today==second_monday or '${{ github.event_name }}'=='workflow_dispatch' else 'false')")" >> $GITHUB_ENV
        shell: bash

      - uses: actions/checkout@v3
        if: env.RUN_JOBS == 'true'
      
      - name: Setup uv
        if: env.RUN_JOBS == 'true'
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --python 3.13
          echo "=== Download Started at $(date) ==="
          echo "System info: $(uname -a)"
          echo "Available memory: $(free -h)"
          echo "Disk space: $(df -h .)"

      - name: Download latest changeset
        if: env.RUN_JOBS == 'true'
        run: |
          wget --progress=dot:giga --timeout=3600 --tries=3 https://planet.openstreetmap.org/planet/changesets-latest.osm.bz2

      - name: Process changeset to table
        if: env.RUN_JOBS == 'true'
        run: |
          # Run the actual processing
          uv run scripts/changeset_to_table.py changesets-latest.osm.bz2 changeset_data_raw
          # delete changeset file after processing to save disk space
          rm -f changesets-latest.osm.bz2
      
      - name: Enrich table
        if: env.RUN_JOBS == 'true'
        run: |
          # Run enrichment for the last complete month
          uv run scripts/enrich_table.py changeset_data_raw changeset_data --last-complete-month
        
      - name: Upload data to Hugging Face
        if: env.RUN_JOBS == 'true'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          bash scripts/upload_to_huggingface.sh